=== goldstack/goldstack/workspaces/apps/packages/goldstack-email-send/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/EmailSendPackage",
  "definitions": {
    "EmailSendPackage": {
      "type": "object",
      "properties": {
        "template": {
          "$ref": "#/definitions/Template"
        },
        "templateVersion": {
          "$ref": "#/definitions/TemplateVersion"
        },
        "name": {
          "$ref": "#/definitions/Name"
        },
        "configuration": {
          "$ref": "#/definitions/EmailSendPackageConfiguration"
        },
        "deployments": {
          "$ref": "#/definitions/EmailSendDeployments"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "configuration",
        "deployments",
        "name",
        "template",
        "templateVersion"
      ],
      "additionalProperties": false,
      "description": "A package for enabling email sends through AWS SES.",
      "title": "Email Send Package"
    },
    "Template": {
      "type": "string",
      "description": "Name of the template used for creating this package.",
      "title": "Template",
      "pattern": "^[^\\s]*$"
    },
    "TemplateVersion": {
      "type": "string",
      "description": "Latest template version that was applied to this package.",
      "title": "Template Version"
    },
    "Name": {
      "type": "string",
      "description": "Name of this package.",
      "title": "Package Name"
    },
    "EmailSendPackageConfiguration": {
      "type": "object",
      "properties": {},
      "description": "Email send package configuration",
      "title": "Email Send Configuration"
    },
    "EmailSendDeployments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/EmailSendDeployment"
      },
      "description": "Places where email send should be configured.",
      "title": "Deployments"
    },
    "EmailSendDeployment": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/DeploymentName"
        },
        "configuration": {
          "$ref": "#/definitions/EmailSendDeploymentConfiguration"
        },
        "terraformVariables": {
          "$ref": "#/definitions/TerraformVariables"
        },
        "awsRegion": {
          "$ref": "#/definitions/AWSDeploymentRegion"
        },
        "awsUser": {
          "$ref": "#/definitions/AWSUserName"
        }
      },
      "required": ["awsRegion", "awsUser", "configuration", "name"]
    },
    "DeploymentName": {
      "type": "string",
      "description": "Identifier for this deployment. No spaces allowed in name.",
      "title": "Deployment Name",
      "pattern": "^[^\\s]*$"
    },
    "EmailSendDeploymentConfiguration": {
      "type": "object",
      "properties": {
        "domain": {
          "type": "string"
        },
        "hostedZoneDomain": {
          "type": "string"
        }
      },
      "required": ["domain", "hostedZoneDomain"]
    },
    "TerraformVariables": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/TerraformVariable"
      },
      "description": "Define which of the deployment variables will be made available for terraform.",
      "title": "Terraform Variables"
    },
    "TerraformVariable": {
      "type": "string",
      "description": "Name of the property that should be converted into a Terraform variable.",
      "title": "Terraform Variable"
    },
    "AWSDeploymentRegion": {
      "type": "string",
      "enum": [
        "us-east-1",
        "us-east-2",
        "us-west-1",
        "us-west-2",
        "af-south-1",
        "ap-east-1",
        "ap-south-1",
        "ap-northeast-3",
        "ap-northeast-2",
        "ap-southeast-1",
        "ap-southeast-2",
        "ap-northeast-1",
        "ca-central-1",
        "eu-central-1",
        "eu-west-1",
        "eu-west-2",
        "eu-south-1",
        "eu-west-3",
        "eu-north-1",
        "me-south-1",
        "sa-east-1"
      ],
      "description": "AWS region that infrastructure should be deployed to.",
      "title": "AWS Deployment Region"
    },
    "AWSUserName": {
      "type": "string",
      "description": "Name of the AWS user that is used to perform the deployment.",
      "title": "AWS User Name"
    }
  }
}

=== goldstack/goldstack/workspaces/apps/packages/goldstack-email-send/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "goldstack-email-send",
  "template": "email-send",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "dev",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "domain": "dev.goldstack.party",
        "hostedZoneDomain": "dev.goldstack.party"
      },
      "tfStateKey": "goldstack-email-send-dev-499ef4e27f7eed892f24.tfstate"
    },
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-prod",
      "configuration": {
        "domain": "goldstack.party",
        "hostedZoneDomain": "goldstack.party"
      },
      "tfStateKey": "goldstack-email-send-prod-4178ace0fd1696262fb4.tfstate"
    }
  ]
}

=== goldstack/goldstack/packages/email-send/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "email-send",
  "template": "email-send",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "domain": "email-send.templates.dev.goldstack.party",
        "hostedZoneDomain": "dev.goldstack.party"
      }
    }
  ]
}
