=== goldstack/goldstack/workspaces/templates/packages/hetzner-vps/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/HetznerVPSPackage",
  "definitions": {
    "HetznerVPSPackage": {
      "type": "object",
      "properties": {
        "template": {
          "$ref": "#/definitions/Template"
        },
        "templateVersion": {
          "$ref": "#/definitions/TemplateVersion"
        },
        "name": {
          "$ref": "#/definitions/Name"
        },
        "configuration": {
          "$ref": "#/definitions/HetznerVPSPackageConfiguration"
        },
        "deployments": {
          "$ref": "#/definitions/HetznerVPSDeployments"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "configuration",
        "deployments",
        "name",
        "template",
        "templateVersion"
      ],
      "additionalProperties": false,
      "description": "A package for provisioning Hetzner servers with Docker.",
      "title": "Email Send Package"
    },
    "Template": {
      "type": "string",
      "description": "Name of the template used for creating this package.",
      "title": "Template",
      "pattern": "^[^\\s]*$"
    },
    "TemplateVersion": {
      "type": "string",
      "description": "Latest template version that was applied to this package.",
      "title": "Template Version"
    },
    "Name": {
      "type": "string",
      "description": "Name of this package.",
      "title": "Package Name"
    },
    "HetznerVPSPackageConfiguration": {
      "type": "object",
      "properties": {},
      "description": "Hetzner VPS package configuration",
      "title": "Hetzner VPS Configuration"
    },
    "HetznerVPSDeployments": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/HetznerVPSDeployment"
      },
      "description": "Configurations for Hetzner VPS deployments.",
      "title": "Deployments"
    },
    "HetznerVPSDeployment": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/DeploymentName"
        },
        "configuration": {
          "$ref": "#/definitions/HetznerVPSDeploymentConfiguration"
        },
        "terraformVariables": {
          "$ref": "#/definitions/TerraformVariables"
        },
        "tfStateKey": {
          "$ref": "#/definitions/TerraformStateKey"
        },
        "tfVersion": {
          "$ref": "#/definitions/TerraformVersion"
        },
        "hetznerUser": {
          "$ref": "#/definitions/HetznerUserName"
        },
        "awsRegion": {
          "$ref": "#/definitions/AWSDeploymentRegion"
        },
        "awsUser": {
          "$ref": "#/definitions/AWSUserName"
        }
      },
      "required": [
        "awsRegion",
        "awsUser",
        "configuration",
        "hetznerUser",
        "name"
      ],
      "description": "Configures a deployment target for the Hetzner server."
    },
    "DeploymentName": {
      "type": "string",
      "description": "Identifier for this deployment. No spaces allowed in name.",
      "title": "Deployment Name",
      "pattern": "^[^\\s]*$"
    },
    "HetznerVPSDeploymentConfiguration": {
      "type": "object",
      "properties": {
        "location": {
          "$ref": "#/definitions/Location"
        },
        "serverType": {
          "$ref": "#/definitions/ServerType"
        },
        "sshUserFingerprint": {
          "$ref": "#/definitions/SSHUserFingerprint"
        },
        "serverName": {
          "$ref": "#/definitions/ServerName"
        },
        "onlyAllowSshAccessFromIp": {
          "$ref": "#/definitions/OnlyAllowSSHAccessFromIP"
        },
        "environmentVariables": {
          "$ref": "#/definitions/EnvironmentVariables"
        }
      },
      "required": [
        "location",
        "serverType",
        "serverName"
      ],
      "description": "The Hetzner server deployment configuration"
    },
    "Location": {
      "type": "string",
      "description": "The Hetzner location this server should be deployed to.",
      "title": "Location",
      "pattern": "^[^\\s]*"
    },
    "ServerType": {
      "type": "string",
      "description": "The Hetzner server type that should be used for this server.",
      "title": "Server Type",
      "pattern": "^[^\\s]*"
    },
    "SSHUserFingerprint": {
      "type": "string",
      "description": "The SSH fingerprint of the SSH user that should be granted access to the server.",
      "title": "SSH User Fingerprint",
      "pattern": "^[^\\s]*"
    },
    "ServerName": {
      "type": "string",
      "description": "The Hetzner server name that should be used for this server.",
      "title": "Server Name",
      "pattern": "^[^\\s]*"
    },
    "OnlyAllowSSHAccessFromIP": {
      "type": "string",
      "description": "Only allow SSH access to the server from the specified IP.",
      "title": "Only allow SSH access from IP"
    },
    "EnvironmentVariables": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/EnvironmentVariable"
      },
      "description": "Environment variables configuration.",
      "title": "Environment Variables"
    },
    "EnvironmentVariable": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/EnvVarName"
        },
        "value": {
          "$ref": "#/definitions/EnvVarValue"
        }
      },
      "required": [
        "name",
        "value"
      ],
      "additionalProperties": false,
      "description": "Environment variable configuration.",
      "title": "Environment Variable"
    },
    "EnvVarName": {
      "type": "string",
      "description": "Environment variable name.",
      "title": "Environment Variable Name",
      "pattern": "^[^\\s]*"
    },
    "EnvVarValue": {
      "type": "string",
      "description": "Environment variable value.",
      "title": "Environment Variable Value"
    },
    "TerraformVariables": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/TerraformVariable"
      },
      "description": "Define which of the deployment variables will be made available for terraform.",
      "title": "Terraform Variables"
    },
    "TerraformVariable": {
      "type": "string",
      "description": "Name of the property that should be converted into a Terraform variable.",
      "title": "Terraform Variable"
    },
    "TerraformStateKey": {
      "type": "string",
      "description": "Key used for Terraform state persisted in Terraform state bucket.\n\nWill be auto-generated upon first deployment if not provided.",
      "title": "Terraform State Key"
    },
    "TerraformVersion": {
      "type": "string",
      "enum": [
        "0.12",
        "0.13",
        "0.14",
        "0.15",
        "1.0",
        "1.1",
        "1.2",
        "1.3",
        "1.4",
        "1.5",
        "1.6",
        "1.7"
      ],
      "description": "Version of Terraform that the remote state for this deployment was created with.\n\nGo to the next version using `yarn infra upgrade [deploymentName] [targetVersion]`. Note that Terraform versions should only be increased one at a time, so for instance you can go from v0.12 to v0.13 but not from v0.12 to v0.14.",
      "default": "0.12"
    },
    "HetznerUserName": {
      "type": "string",
      "description": "Name of the Hetzner user that is used to perform the deployment.",
      "title": "Hetzner User Name"
    },
    "AWSDeploymentRegion": {
      "type": "string",
      "enum": [
        "us-east-1",
        "us-east-2",
        "us-west-1",
        "us-west-2",
        "af-south-1",
        "ap-east-1",
        "ap-south-1",
        "ap-northeast-3",
        "ap-northeast-2",
        "ap-southeast-1",
        "ap-southeast-2",
        "ap-northeast-1",
        "ca-central-1",
        "eu-central-1",
        "eu-west-1",
        "eu-west-2",
        "eu-south-1",
        "eu-west-3",
        "eu-north-1",
        "me-south-1",
        "sa-east-1"
      ],
      "description": "AWS region that infrastructure should be deployed to.",
      "title": "AWS Deployment Region"
    },
    "AWSUserName": {
      "type": "string",
      "description": "Name of the AWS user that is used to perform the deployment.",
      "title": "AWS User Name"
    }
  }
}

=== goldstack/goldstack/workspaces/templates/packages/hetzner-vps/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "hetzner-vps",
  "template": "hetzner-vps",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "hetznerUser": "max",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "location": "hil",
        "serverType": "cpx11",
        "sshUserFingerprint": "73:db:08:81:7f:fe:34:c3:40:2e:10:d0:89:a7:b7:12",
        "serverName": "goldstack-docker",
        "onlyAllowSshAccessFromIp": "210.50.200.68",
        "environmentVariables": [
          {
            "name": "DUMMY_ENV",
            "value": "I rock"
          },
          {
            "name": "HTTP_PORT",
            "value": "80"
          },
          {
            "name": "HTTPS_PORT",
            "value": "443"
          }
        ]
      },
      "tfStateKey": "hetzner-docker-prod-c7e278526542d31fcdec.tfstate"
    }
  ]
}
