=== goldstack/goldstack/workspaces/templates/packages/backup-central/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Package",
  "definitions": {
    "Package": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "template": {
          "type": "string"
        },
        "templateVersion": {
          "type": "string"
        },
        "configuration": {
          "$ref": "package-configuration.schema.json#/definitions/PackageConfiguration"
        },
        "deployments": {
          "type": "array",
          "items": {
            "$ref": "deployment.schema.json#/definitions/Deployment"
          }
        }
      },
      "required": ["$schema", "name", "template", "templateVersion", "configuration", "deployments"]
    }
  }
}

=== goldstack/goldstack/workspaces/templates/packages/user-management/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "user-management",
  "template": "user-management",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "cognitoDomain": "auth-example-v2.dev.goldstack.party",
        "userPoolName": "example-pool-v2",
        "cookieDomain": ".dev.goldstack.party",
        "cookieSameSite": "None",
        "hostedZoneDomain": "dev.goldstack.party",
        "callbackUrl": "https://ssr.examples.templates.dev.goldstack.party",
        "deletionProtection": false
      },
      "tfStateKey": "user-management-prod-c24c67342f629ac2217b.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/lambda-go-gin/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "lambda-go-gin-template",
  "template": "lambda-go-gin",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "lambdaName": "goldstack-test-lambda-go-gin",
        "apiDomain": "go-gin-api.templates.dev.goldstack.party",
        "hostedZoneDomain": "dev.goldstack.party",
        "cors": "https://app-nextjs-bootstrap.templates.dev.goldstack.party"
      },
      "tfStateKey": "lambda-go-gin-template-prod-e346f6ec1a6c006baaa0.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/lambda-python-job/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "lambda-python-job",
  "template": "lambda-python-job",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "lambdaName": "lambda-python-job-test",
        "schedule": "rate(1 minute)",
        "sqsQueueName": "lambda-python-job-sqs-test"
      },
      "tfVersion": "1.14.7",
      "tfStateKey": "lambda-python-job-prod-279b0e980347eb11b01d.tfstate"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/lambda-node-trigger/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "lambda-node-trigger",
  "template": "lambda-node-trigger",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "lambdaName": "lambda-node-trigger-test",
        "schedule": "rate(1 day)",
        "sqsQueueName": "lambda-node-trigger-sqs-test"
      },
      "tfVersion": "1.14.7",
      "tfStateKey": "lambda-node-trigger-prod-5001cd04b339e4a7da56.tfstate"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/s3/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "s3",
  "template": "s3",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "bucketName": "goldstack-test-s3-bucket"
      },
      "tfStateKey": "s3-prod-40dd578eab44b83dc601.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/dynamodb/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "dynamodb",
  "template": "dynamodb",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "tableName": "goldstack-test-dynamodb-table"
      },
      "tfVersion": "1.14.7",
      "tfStateKey": "dynamodb-prod-edaaa7b3e6697ea8adba.tfstate"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/backup-central/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "backup-central",
  "template": "backup-central",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-east-1",
      "awsUser": "goldstack-backup",
      "configuration": {
        "backupVaultName": "goldstack-central-vault",
        "allowedAccountIds": ["475629728374"],
        "sourceAccountIds": ["475629728374"],
        "sourceRoleArns": ["arn:aws:iam::475629728374:role/GoldstackBackupRole"]
      },
      "tfVersion": "1.14.7",
      "tfStateKey": "backup-central-prod-1461e0ceb8269ee68939.tfstate"
    }
  ]
}

=== goldstack/goldstack/workspaces/templates/packages/server-side-rendering/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "server-side-rendering",
  "template": "server-side-rendering",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "lambdaNamePrefix": "goldstack-test-ssr-v2",
        "domain": "ssr-v2.examples.templates.dev.goldstack.party",
        "hostedZoneDomain": "dev.goldstack.party",
        "cors": "https://app-nextjs-bootstrap.templates.dev.goldstack.party",
        "lambdas": {
          "ANY /": {
            "function_name": "goldstack-test-ssr-v2-__index",
            "route": "ANY /"
          },
          "ANY /posts": {
            "function_name": "goldstack-test-ssr-v2-posts",
            "route": "ANY /posts"
          },
          "ANY /robots.txt": {
            "function_name": "goldstack-test-ssr-v2-robots_txt",
            "route": "ANY /robots.txt"
          }
        }
      },
      "tfStateKey": "server-side-rendering-prod-cef430073a2474be1434.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}
