=== goldstack/goldstack/workspaces/templates/packages/backup-central/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Package",
  "definitions": {
    "Package": {
      "type": "object",
      "properties": {
        "$schema": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "template": {
          "type": "string"
        },
        "templateVersion": {
          "type": "string"
        },
        "configuration": {
          "$ref": "package-configuration.schema.json#/definitions/PackageConfiguration"
        },
        "deployments": {
          "type": "array",
          "items": {
            "$ref": "deployment.schema.json#/definitions/Deployment"
          }
        }
      },
      "required": ["$schema", "name", "template", "templateVersion", "configuration", "deployments"]
    }
  }
}

=== goldstack/goldstack/workspaces/templates/packages/email-send/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "email-send",
  "template": "email-send",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "domain": "email-send-v2.templates.dev.goldstack.party",
        "hostedZoneDomain": "dev.goldstack.party"
      },
      "tfStateKey": "email-send-prod-c1356c7f30852453a420.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}
