=== goldstack/goldstack/workspaces/docs/packages/cdn/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ThisPackage",
  "definitions": {
    "ThisPackage": {
      "type": "object",
      "properties": {
        "template": {
          "$ref": "#/definitions/Template"
        },
        "templateVersion": {
          "$ref": "#/definitions/TemplateVersion"
        },
        "name": {
          "$ref": "#/definitions/Name"
        },
        "configuration": {
          "$ref": "#/definitions/ThisPackageConfiguration"
        },
        "deployments": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ThisDeployment"
          }
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "$schema",
        "configuration",
        "deployments",
        "name",
        "template",
        "templateVersion"
      ],
      "additionalProperties": false,
      "description": "A AWS Static Website Package.",
      "title": "AWS Static Website Package"
    },
    "Template": {
      "type": "string",
      "description": "Name of the template used for creating this package.",
      "title": "Template",
      "pattern": "^[^\\s]*$"
    },
    "TemplateVersion": {
      "type": "string",
      "description": "Latest template version that was applied to this package.",
      "title": "Template Version"
    },
    "Name": {
      "type": "string",
      "description": "Name of this package.",
      "title": "Package Name"
    },
    "ThisPackageConfiguration": {
      "type": "object",
      "properties": {},
      "description": "Configures a static website hosted on AWS.",
      "title": "AWS Static Website Configuration"
    },
    "ThisDeployment": {
      "type": "object",
      "properties": {
        "name": {
          "$ref": "#/definitions/DeploymentName"
        },
        "configuration": {
          "$ref": "#/definitions/ThisDeploymentConfiguration"
        },
        "terraformVariables": {
          "$ref": "#/definitions/TerraformVariables"
        },
        "awsRegion": {
          "$ref": "#/definitions/AWSDeploymentRegion"
        },
        "awsUser": {
          "$ref": "#/definitions/AWSUserName"
        }
      },
      "required": ["awsRegion", "awsUser", "configuration", "name"],
      "description": "Configures a static website deployment.",
      "title": "Deployment"
    },
    "DeploymentName": {
      "type": "string",
      "description": "Identifier for this deployment. No spaces allowed in name.",
      "title": "Deployment Name",
      "pattern": "^[^\\s]*$"
    },
    "ThisDeploymentConfiguration": {
      "type": "object",
      "properties": {
        "hostedZoneDomain": {
          "$ref": "#/definitions/HostedZoneDomain"
        },
        "websiteDomain": {
          "$ref": "#/definitions/PrimaryWebsiteDomain"
        },
        "websiteDomainRedirect": {
          "$ref": "#/definitions/RedirectWebsiteDomain"
        },
        "defaultCacheDuration": {
          "$ref": "#/definitions/DefaultCacheDuration"
        }
      },
      "required": ["hostedZoneDomain", "websiteDomain", "websiteDomainRedirect"]
    },
    "HostedZoneDomain": {
      "type": "string",
      "description": "The domain name of the Route 53 hosted zone that this website should be added to.",
      "title": "Hosted Zone Domain"
    },
    "PrimaryWebsiteDomain": {
      "type": "string",
      "description": "The domain name your users should use (e.g. mysite.com)",
      "title": "Primary Website Domain"
    },
    "RedirectWebsiteDomain": {
      "type": "string",
      "description": "A domain name that users are redirected from to your Primary Website Domain (e.g. www.mysite.com)",
      "title": "Redirect Website Domain"
    },
    "DefaultCacheDuration": {
      "type": "number",
      "description": "Seconds resources will be cached for by default. For development sites, a good value is around 10 seconds and for production sites 60-100 seconds.",
      "title": "Default Cache Duraction",
      "exclusiveMinimum": 0
    },
    "TerraformVariables": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/TerraformVariable"
      },
      "description": "Define which of the deployment variables will be made available for terraform.",
      "title": "Terraform Variables"
    },
    "TerraformVariable": {
      "type": "string",
      "description": "Name of the property that should be converted into a Terraform variable.",
      "title": "Terraform Variable"
    },
    "AWSDeploymentRegion": {
      "type": "string",
      "enum": [
        "us-east-1",
        "us-east-2",
        "us-west-1",
        "us-west-2",
        "af-south-1",
        "ap-east-1",
        "ap-south-1",
        "ap-northeast-3",
        "ap-northeast-2",
        "ap-southeast-1",
        "ap-southeast-2",
        "ap-northeast-1",
        "ca-central-1",
        "eu-central-1",
        "eu-west-1",
        "eu-west-2",
        "eu-south-1",
        "eu-west-3",
        "eu-north-1",
        "me-south-1",
        "sa-east-1"
      ],
      "description": "AWS region that infrastructure should be deployed to.",
      "title": "AWS Deployment Region"
    },
    "AWSUserName": {
      "type": "string",
      "description": "Name of the AWS user that is used to perform the deployment.",
      "title": "AWS User Name"
    }
  }
}

=== goldstack/goldstack/packages/cdn/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "goldstack-cdn",
  "template": "static-website-aws",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "dev",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "defaultCacheDuration": 1,
        "hostedZoneDomain": "dev.goldstack.party",
        "websiteDomain": "cdn.dev.goldstack.party",
        "websiteDomainRedirect": "www.cdn.dev.goldstack.party"
      }
    },
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-prod",
      "configuration": {
        "defaultCacheDuration": 1,
        "hostedZoneDomain": "goldstack.party",
        "websiteDomain": "cdn.goldstack.party",
        "websiteDomainRedirect": "www.cdn.goldstack.party"
      }
    }
  ]
}

=== goldstack/goldstack/workspaces/docs/packages/docs-main/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "app-nextjs-bootstrap",
  "template": "app-nextjs-bootstrap",
  "templateVersion": "0.1.8",
  "configuration": {},
  "deployments": [
    {
      "name": "dev",
      "configuration": {
        "hostedZoneDomain": "dev.goldstack.party",
        "websiteDomain": "docs.dev.goldstack.party",
        "websiteDomainRedirect": "www.docs.dev.goldstack.party",
        "defaultCacheDuration": 10,
        "environmentVariables": [
          {
            "name": "NEXT_PUBLIC_GOLDSTACK_HOME",
            "value": "https://dev.goldstack.party"
          }
        ]
      },
      "awsUser": "goldstack-dev",
      "awsRegion": "us-west-2",
      "tfStateKey": "app-nextjs-bootstrap-dev-f53056a4648c8eb7a1ac.tfstate",
      "tfVersion": "1.14.7"
    },
    {
      "name": "prod",
      "configuration": {
        "hostedZoneDomain": "goldstack.party",
        "websiteDomain": "docs.goldstack.party",
        "websiteDomainRedirect": "www.docs.goldstack.party",
        "defaultCacheDuration": 10,
        "environmentVariables": [
          {
            "name": "NEXT_PUBLIC_GOLDSTACK_HOME",
            "value": "https://goldstack.party"
          }
        ]
      },
      "awsUser": "goldstack-prod",
      "awsRegion": "us-west-2",
      "tfStateKey": "app-nextjs-bootstrap-prod-8840af844f84652e29f6.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}

=== goldstack/goldstack/workspaces/apps/packages/goldstack-home/goldstack.json
{
  "$schema": "./schemas/package.schema.json",
  "name": "goldstack-home",
  "template": "app-nextjs-bootstrap",
  "templateVersion": "0.1.0",
  "configuration": {},
  "deployments": [
    {
      "name": "dev",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-dev",
      "configuration": {
        "hostedZoneDomain": "dev.goldstack.party",
        "websiteDomain": "dev.goldstack.party",
        "websiteDomainRedirect": "www.dev.goldstack.party",
        "defaultCacheDuration": 10,
        "environmentVariables": [
          {
            "name": "NEXT_PUBLIC_GOLDSTACK_DOCS",
            "value": "https://docs.dev.goldstack.party/docs"
          },
          {
            "name": "NEXT_PUBLIC_STRIPE_PUBLIC_API_KEY",
            "value": "pk_test_51Hd1UtArOjAVQR9vxRvGfIEMGJIvY82W0PHB7ajEjh4kIHXU148UsKthSk5b6itbWR5mSg74NvfmdKdDBqItQ01m00Av3f7gpd"
          }
        ]
      },
      "tfStateKey": "goldstack-home-dev-181bf9be096a2f5c100d.tfstate",
      "tfVersion": "1.14.7"
    },
    {
      "name": "prod",
      "awsRegion": "us-west-2",
      "awsUser": "goldstack-prod",
      "configuration": {
        "hostedZoneDomain": "goldstack.party",
        "websiteDomain": "goldstack.party",
        "websiteDomainRedirect": "www.goldstack.party",
        "defaultCacheDuration": 10,
        "environmentVariables": [
          {
            "name": "NEXT_PUBLIC_GOLDSTACK_DOCS",
            "value": "https://docs.goldstack.party/docs"
          },
          {
            "name": "NEXT_PUBLIC_STRIPE_PUBLIC_API_KEY",
            "value": "pk_live_51Hd1UtArOjAVQR9vhVCzlap2C2bNTAdFM6D30iZB8xeNmEYSy0Tuw4q0uAaeXL562EZesN7fx0HiG2HMBjenzTqq00y9qiR4WI"
          }
        ]
      },
      "tfStateKey": "goldstack-home-prod-af8fc0afddf00dd7793c.tfstate",
      "tfVersion": "1.14.7"
    }
  ]
}
